version: "3"

services:
  app:
    build: .
    command: npm run start:dev
    ports:
      - "${APP_PORT}:8080"
    volumes:
      - .:/usr/app

  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '${DB_PORT}:5432'
    volumes:
        - ./sql/1646769518-create-database.sql:/docker-entrypoint-initdb.d/1646769518-create-database.sql