CREATE TABLE customer (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	first_name VARCHAR(30) NOT NULL,
	last_name VARCHAR(40) NOT NULL,
	document VARCHAR(14) NOT NULL UNIQUE,
	email VARCHAR(60) NOT NULL,
	password VARCHAR NOT NULL,
	balance DECIMAL(5,2) NOT NULL DEFAULT 0,
	enabled BOOLEAN NULL DEFAULT TRUE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT NULL,
	disabled_at TIMESTAMP DEFAULT NULL
);

CREATE TABLE address (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	customer_id BIGINT NOT NULL,
	cep CHAR(8) NOT NULL,
	alias VARCHAR(50),
	street_name VARCHAR(100) NOT NULL,
	street_number VARCHAR(5) NOT NULL,
	complement VARCHAR(100),
	reference VARCHAR(100),
	district VARCHAR(50) NOT NULL,
	city VARCHAR(50) NOT NULL,
	uf CHAR(2) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT NULL,
	FOREIGN KEY (customer_id) REFERENCES customer (id)
);

CREATE TABLE phone (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	customer_id BIGINT NOT NULL,
	phone_number NUMERIC(11) NOT NULL UNIQUE,
	enabled BOOLEAN NOT NULL DEFAULT TRUE,
	FOREIGN KEY (customer_id) REFERENCES customer (id)

);


CREATE TABLE redeem_code (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	customer_id BIGINT NOT NULL,
	code VARCHAR NOT NULL UNIQUE,
	value DECIMAL(5,2) NOT NULL,
	is_redeemed BOOLEAN NOT NULL DEFAULT FALSE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT NULL,
	FOREIGN KEY (customer_id) REFERENCES customer (id)

);

CREATE TABLE "order" (
	id BIGSERIAL NOT NULL PRIMARY KEY, 
	code VARCHAR NOT NULL UNIQUE,
	status VARCHAR NOT NULL,
	nfe VARCHAR(255) NOT NULL UNIQUE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT NULL,
	address_id BIGSERIAL NOT NULL,
	costumer_id BIGSERIAL NOT NULL,
	FOREIGN KEY (address_id) REFERENCES address (id),
	FOREIGN KEY (costumer_id) REFERENCES customer (id)
);

CREATE TABLE product (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	name varchar(100) NOT NULL UNIQUE,
	manufacturer VARCHAR(50) NOT NULL,
	price DECIMAL(5,2) NOT NULL,
	inventory INTEGER NOT NULL DEFAULT 0,
	description TEXT NOT NULL,
	specification TEXT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT NULL
);

CREATE TABLE order_product (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	order_id BIGINT NOT NULL,
	product_id BIGINT NOT NULL,
	FOREIGN KEY (order_id) REFERENCES "order" (id),
	FOREIGN KEY (product_id) REFERENCES product (id)
);

CREATE TABLE rating (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	stars SMALLINT NOT NULL,
	costumer_name VARCHAR (50) NOT NULL,
	description TEXT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT NULL,
	product_id BIGSERIAL NOT NULL,
	FOREIGN KEY (product_id) REFERENCES product (id)
);

CREATE TABLE category (	
	id BIGINT NOT NULL PRIMARY KEY,
	description VARCHAR(255)
);

CREATE TABLE product_category (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	product_id BIGSERIAL NOT NULL,
	category_id BIGSERIAL NOT NULL,
	FOREIGN KEY (product_id) REFERENCES product (id),
	FOREIGN KEY (category_id) REFERENCES category (id)
);